better summary

diff --git a/.github/workflows/matrix-test.yml b/.github/workflows/matrix-test.yml
--- a/.github/workflows/matrix-test.yml
+++ b/.github/workflows/matrix-test.yml
@@ -75,8 +75,17 @@ jobs:
     name: "Summarize CI Run"
     needs:
       - run
+      - setup
     runs-on: ubuntu-latest
     steps:
       - name: "summarize"
         run: |
-          echo The CI run has ${{ needs.run.result }}
+          echo " Test Summary"
+          echo "--------------------------------"
+          echo "Test Combinations:"
+          echo "${{ needs.setup.outputs.matrix }}"
+          echo "--------------------------------"
+          if [[ "${{ needs.run.result }}" != "success" && "${{ needs.run.result }}" != "skipped" ]]; then
+            echo "Some provisioning tests failed. Please check the logs for details."
+            exit 1
+          fi
